version: '3'
services:
  frontend:
    image: nginx:1.14.1
    volumes:
      # Site
      - ./frontend:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
  backend:
    image: node:10.13.0
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: node_modules/.bin/nodemon dist/app.js
    ports:
      - 3000:3000